export const MenuItems = [
    ["File", [
        ["New", "new-map"],
        [],
        ["Open...", "show-explorer"],
        [],
        ["Save", "save"],
        ["Save As...", "save-as"],
        ["Download...", "save-download"],
        [],
        ["Export", "export"],
        ["Export As...", "export-as"],
        ["Export Download...", "export-download"],
    ]],
    ["Edit", [
        ["Undo", "undo"],
        ["Redo", "redo"],
        [],
        ["Delete", "delete"],
        [],
        ["Cut", "cut"],
        ["Copy", "copy"],
        ["Paste", "paste"],
    ]],
    ["Selection", [
        ["Switch Vertices/Polygons", "selection-vert-switch"],
    ]],
    ["Object", [
        ["Texture", [
            ["Reset", "texture-reset"],
            [],
            ["Rotate 90° CW", "texture-rotate-90-cw"],
            ["Rotate 90° CCW", "texture-rotate-90-ccw"],
            ["Flip Horizontal", "texture-flip-horizontal"],
            ["Flip Vertical", "texture-flip-vertical"],
        ]],
        [],
        ["Rotate 90° CW", "rotate-90-cw"],
        ["Rotate 90° CCW", "rotate-90-ccw"],
        ["Flip Horizontal", "flip-horizontal"],
        ["Flip Vertical", "flip-vertical"],
        [],
        ["Send to Back", "send-to-back"],
        ["Send Backward", "send-backward"],
        ["Bring Forward", "bring-forward"],
        ["Bring to Front", "bring-to-front"],
    ]],
    ["View", [
        ["Reset Viewport", "reset-viewport"],
        ["Zoom In", "zoom-in"],
        ["Zoom Out", "zoom-out"],
        [],
        ["Snap to Grid", "toggle-snap-to-grid"],
        ["Snap to Objects", "toggle-snap-to-objects"],
        [],
        ["Show Grid", "toggle-grid"],
        ["Show Background", "toggle-background"],
        ["Show Vertices", "toggle-vertices"],
        ["Show Wireframe", "toggle-wireframe"],
        ["Polygons", [
            ["Texture", "show-polygon-texture"],
            ["Plain Color", "show-polygon-plain"],
            ["Hide", "show-polygon-none"],
        ]],
    ]],
    ["Help", [
        ["Github", "browse-to-github"],
    ]],
];
